# These environment variables must be set in CircleCI UI
#
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
# Read the README for more information.
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/justinagain/deployer
    branches:
      only:
        - master
    steps:

    - test:
      override:
        - >
            go test
            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        # Go applications in the busybox container must be built statically
        - >
            go install --ldflags '-extldflags "-static"'
            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
        - '[ ! -e bin ] && mkdir bin'
        - cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer
        - chmod +x deploymentTests/*
        - docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .

        # Run GOVEND to check if outdated dependencies are present
        - 'GOPATH="$GOPATH_HEAD"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u && git diff --quiet )'

    - deployment:
      hub_latest:
        # appropriately tag and push the container to dockerhub
        # only when on the master branch
        branch: "master"
        commands:
          - >
              docker login -e ${DOCKER_EMAIL}
              -u ${DOCKER_USER} -p ${DOCKER_PASS}
          # write the sha256 sum to an artifact to make image verification easier
          - >
            docker images --no-trunc | awk '/^app/ {print $3}' |
            tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt
          - docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}

          # trigger ebs redeploy
          #- aws elasticbeanstalk update-environment --region us-east-1 --application-name invoicer201707071231 --environment-id e-h4vyur8nup --version-label deployer-api

